// Generated by generateDemo task, DO NOT MODIFY
package org.example.eff.df.parents.demos


/**
 * Case: Case(sn=1075, classAnnoOnSuper=None, originMethodInSuper=None, handlerInSuper=None, classAnnoOnClass=None, originMethodInClass=WithAnnoHavingAttr, hasHandlerInClass=true)
 */
abstract class Case1075KotlinSuperForJava
