// Generated by generateDemo task, DO NOT MODIFY
package org.example.eff.df.parents.demos

import org.springframework.stereotype.Component

/**
 * Case: Case(sn=0885, classAnnoOnSuper=None, originMethodInSuper=WithAnnoNoAttrWithBody, handlerInSuper=None, classAnnoOnClass=None, originMethodInClass=None, hasHandlerInClass=false)
 */
@Component
class Case0885KotlinSuperKotlinDemo : Case0885KotlinSuperForKotlin()
