// Generated by generateDemo task, DO NOT MODIFY
package org.example.eff.df.parents.demos


/**
 * Case: Case(sn=1046, classAnnoOnSuper=None, originMethodInSuper=None, handlerInSuper=WithBody, classAnnoOnClass=WithoutAttr, originMethodInClass=WithoutAnno, hasHandlerInClass=true)
 */
abstract class Case1046KotlinSuperForKotlin
