// Generated by generateDemo task, DO NOT MODIFY
package org.example.eff.df.parents.demos


/**
 * Case: Case(sn=1080, classAnnoOnSuper=None, originMethodInSuper=None, handlerInSuper=None, classAnnoOnClass=None, originMethodInClass=WithoutAnno, hasHandlerInClass=false)
 */
abstract class Case1080KotlinSuperForJava
