rootProject.name = "sentinel-plays"
include("play-basic")
include("play-block-handler")
include("play-class-default")
include("play-default-fallback")
include("play-effectiveness-block-basic")
include("play-effectiveness-default-fallback-basic")
include("play-effectiveness-fallback-basic")
include("play-fallback-shadow")
include("play-handler-classes")
include("play-openfeign-cloud")
include("play-openfeign-simple")
include("play-param-conflicts")
include("play-return-conflicts")
include("play-web-cloud")
