rootProject.name = "sentinel-plays"
include("play-basic")
include("play-class-default")
include("play-default-fallback")
include("play-fallback-shadow")
include("play-openfeign-simple")
include("play-openfeign-cloud")
include("play-param-conflicts")
include("play-return-conflicts")
include("play-web-cloud")
