// Generated by generateDemo task, DO NOT MODIFY
package org.example.eff.df.parents.demos;

import org.springframework.stereotype.Component;

/**
 * Case: Case(sn=0489, classAnnoOnSuper=WithoutAttr, originMethodInSuper=WithAnnoNoAttrWithBody, handlerInSuper=WithBody, classAnnoOnClass=None, originMethodInClass=None, hasHandlerInClass=false)
 */
@SuppressWarnings("unused")
@Component
public class Case0489KotlinSuperJavaDemo extends Case0489KotlinSuperForJava {

}
