// Generated by generateDemo task, DO NOT MODIFY
package org.example.eff.df.parents.demos;

import org.springframework.stereotype.Component;

/**
 * Case: Case(sn=0270, classAnnoOnSuper=WithAttr, originMethodInSuper=WithoutAnnoWithBody, handlerInSuper=None, classAnnoOnClass=None, originMethodInClass=None, hasHandlerInClass=false)
 */
@SuppressWarnings("unused")
@Component
public class Case0270KotlinSuperJavaDemo extends Case0270KotlinSuperForJava {

}
