// Generated by generateDemo task, DO NOT MODIFY
package org.example.eff.block.interfaces.jdk.demos

import org.springframework.stereotype.Component

/**
 * Case: Case(sn=180, hasClassAnnoOnSuper=true, originMethodInSuper=WithoutAnnoWithBody, handlerInSuper=None, hasClassAnnoOnClass=false, originMethodInClass=None, hasHandlerInClass=false)
 */
@Component
class Case180JavaInterfaceKotlinDemo : Case180JavaInterfaceForKotlin
