// Generated by generateDemo task, DO NOT MODIFY
package org.example.eff.fallback.parents.demos;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;


/**
 * Case: Case(sn=435, hasClassAnnoOnSuper=false, originMethodInSuper=WithoutAnnoAbstract, handlerInSuper=Abstract, hasClassAnnoOnClass=true, originMethodInClass=WithoutAnno, hasHandlerInClass=true)
 */
@SuppressWarnings("unused")
public abstract class Case435JavaSuperForJava {

    @NotNull
    public abstract String greeting(@Nullable String name);

    @NotNull
    public abstract String classHandler(@Nullable String name, @Nullable Throwable e);

    @NotNull
    public abstract String classHandler(@Nullable String name);

}
