// Generated by generateDemo task, DO NOT MODIFY
package org.example.eff.fallback.parents.demos;



/**
 * Case: Case(sn=476, hasClassAnnoOnSuper=false, originMethodInSuper=None, handlerInSuper=None, hasClassAnnoOnClass=false, originMethodInClass=WithAnnoHavingAttr, hasHandlerInClass=false)
 */
@SuppressWarnings("unused")
public abstract class Case476JavaSuperForJava {

}
