// Generated by generateDemo task, DO NOT MODIFY
package org.example.eff.df.interfaces.cglib.demos;

import org.springframework.stereotype.Component;

/**
 * Case: Case(sn=0384, classAnnoOnSuper=WithoutAttr, originMethodInSuper=WithAnnoHavingAttrWithBody, handlerInSuper=WithBody, classAnnoOnClass=None, originMethodInClass=None, hasHandlerInClass=false)
 */
@SuppressWarnings("unused")
@Component
public class Case0384JavaInterfaceJavaDemo implements Case0384JavaInterfaceForJava {

}
