// Generated by generateDemo task, DO NOT MODIFY
package org.example.eff.df.interfaces.jdk.demos;

import org.springframework.stereotype.Component;

/**
 * Case: Case(sn=0795, classAnnoOnSuper=None, originMethodInSuper=WithAnnoNoAttrWithBody, handlerInSuper=None, classAnnoOnClass=None, originMethodInClass=None, hasHandlerInClass=false)
 */
@SuppressWarnings("unused")
@Component
public class Case0795KotlinInterfaceJavaDemo implements Case0795KotlinInterfaceForJava {

}
