// Generated by generateDemo task, DO NOT MODIFY
package org.example.eff.block.parents.demos

import org.springframework.stereotype.Component

/**
 * Case: Case(sn=040, hasClassAnnoOnSuper=true, originMethodInSuper=WithAnnoHavingAttrWithBody, handlerInSuper=None, hasClassAnnoOnClass=false, originMethodInClass=None, hasHandlerInClass=false)
 */
@Component
class Case040KotlinSuperKotlinDemo : Case040KotlinSuperForKotlin()
