// Generated by generateDemo task, DO NOT MODIFY
package org.example.eff.block.parents.demos

import com.alibaba.csp.sentinel.slots.block.BlockException

/**
 * Case: Case(sn=434, hasClassAnnoOnSuper=false, originMethodInSuper=WithoutAnnoAbstract, handlerInSuper=Abstract, hasClassAnnoOnClass=true, originMethodInClass=WithAnnoNoAttr, hasHandlerInClass=true)
 */
abstract class Case434KotlinSuperForKotlin {

    abstract fun greeting(name: String?): String

    abstract fun classHandler(name: String?, e: BlockException?): String

}
