// Generated by generateDemo task, DO NOT MODIFY
package org.example.eff.block.parents.demos

import com.alibaba.csp.sentinel.slots.block.BlockException

/**
 * Case: Case(sn=436, hasClassAnnoOnSuper=false, originMethodInSuper=WithoutAnnoAbstract, handlerInSuper=Abstract, hasClassAnnoOnClass=false, originMethodInClass=WithAnnoHavingAttr, hasHandlerInClass=true)
 */
abstract class Case436KotlinSuperForJava {

    abstract fun greeting(name: String?): String

    abstract fun methodHandler(name: String?, e: BlockException?): String

}
