// Generated by generateDemo task, DO NOT MODIFY
package org.example.eff.block.parents.demos


/**
 * Case: Case(sn=477, hasClassAnnoOnSuper=false, originMethodInSuper=None, handlerInSuper=None, hasClassAnnoOnClass=false, originMethodInClass=WithAnnoNoAttr, hasHandlerInClass=true)
 */
abstract class Case477KotlinSuperForKotlin
