// Generated by generateDemo task, DO NOT MODIFY
package org.example.eff.fallback.parents.demos

import org.springframework.stereotype.Component

/**
 * Case: Case(sn=404, hasClassAnnoOnSuper=false, originMethodInSuper=WithoutAnnoWithBody, handlerInSuper=Abstract, hasClassAnnoOnClass=false, originMethodInClass=None, hasHandlerInClass=true)
 */
@Component
class Case404JavaSuperKotlinDemo : Case404JavaSuperForKotlin()
