// Generated by generateDemo task, DO NOT MODIFY
package org.example.eff.fallback.parents.demos

import org.springframework.stereotype.Component

/**
 * Case: Case(sn=110, hasClassAnnoOnSuper=true, originMethodInSuper=WithAnnoNoAttrWithBody, handlerInSuper=None, hasClassAnnoOnClass=false, originMethodInClass=None, hasHandlerInClass=false)
 */
@Component
class Case110KotlinSuperKotlinDemo : Case110KotlinSuperForKotlin()
