// Generated by generateDemo task, DO NOT MODIFY
package org.example.eff.fallback.parents.demos

import org.springframework.stereotype.Component

/**
 * Case: Case(sn=016, hasClassAnnoOnSuper=true, originMethodInSuper=WithAnnoHavingAttrWithBody, handlerInSuper=WithBody, hasClassAnnoOnClass=false, originMethodInClass=None, hasHandlerInClass=false)
 */
@Component
class Case016JavaSuperKotlinDemo : Case016JavaSuperForKotlin()
