// Generated by generateDemo task, DO NOT MODIFY
package org.example.eff.df.interfaces.jdk.demos

import org.springframework.stereotype.Component

/**
 * Case: Case(sn=390, hasClassAnnoOnSuper=false, originMethodInSuper=WithoutAnnoWithBody, handlerInSuper=None, hasClassAnnoOnClass=false, originMethodInClass=None, hasHandlerInClass=false)
 */
@Component
class Case390JavaInterfaceKotlinDemo : Case390JavaInterfaceForKotlin
